WIDTH_FIELD = 40
HEIGHT_FIELD = 25
HEIGHT_PANEL = 80
MARGIN = 20
MARGIN_WIDTH = 7

MINES = 200
SIZE_CELL = 32

WIDTH = WIDTH_FIELD * SIZE_CELL + 2 * MARGIN + 2 * MARGIN_WIDTH
HEIGHT = HEIGHT_FIELD * SIZE_CELL + HEIGHT_PANEL + 3 * MARGIN + 4 * MARGIN_WIDTH

CAPTION = 'Minesweeper'
FPS = 15
